# Generated by Django 5.2.1 on 2025-05-22 18:21

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('registration_number', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Transport',
                'verbose_name_plural': 'Transport',
            },
        ),
        migrations.CreateModel(
            name='RentalApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text="Renter's full name", max_length=200)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(help_text='Contact phone number', max_length=128, region=None)),
                ('rental_start_date', models.DateField(help_text='Start date of rental')),
                ('rental_end_date', models.DateField(help_text='End date of rental')),
                ('passport_number', models.CharField(help_text='Passport number', max_length=50)),
                ('passport_issued_by', models.CharField(help_text='Authority that issued the passport', max_length=200)),
                ('passport_issue_date', models.DateField(help_text='Date when passport was issued')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rental_applications', to='rentals.transport')),
            ],
            options={
                'verbose_name': 'Rental Application',
                'verbose_name_plural': 'Rental Applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
