# Generated by Django 5.2.1 on 2025-05-22 18:27

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentalapplication',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заявка на аренду', 'verbose_name_plural': 'Заявки на аренду'},
        ),
        migrations.AlterModelOptions(
            name='transport',
            options={'verbose_name': 'Транспорт', 'verbose_name_plural': 'Транспорт'},
        ),
        migrations.AlterField(
            model_name='rentalapplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='rentalapplication',
            name='full_name',
            field=models.CharField(help_text='Полное имя арендатора', max_length=200, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='rentalapplication',
            name='passport_issue_date',
            field=models.DateField(help_text='Дата выдачи паспорта', verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='rentalapplication',
            name='passport_issued_by',
            field=models.CharField(help_text='Орган, выдавший паспорт', max_length=200, verbose_name='Кем выдан'),
        ),
        migrations.AlterField(
            model_name='rentalapplication',
            name='passport_number',
            field=models.CharField(help_text='Номер паспорта', max_length=50, verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='rentalapplication',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Контактный номер телефона', max_length=128, region=None, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='rentalapplication',
            name='rental_end_date',
            field=models.DateField(help_text='Дата окончания аренды', verbose_name='Дата окончания аренды'),
        ),
        migrations.AlterField(
            model_name='rentalapplication',
            name='rental_start_date',
            field=models.DateField(help_text='Дата начала аренды', verbose_name='Дата начала аренды'),
        ),
        migrations.AlterField(
            model_name='rentalapplication',
            name='transport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rental_applications', to='rentals.transport', verbose_name='Транспорт'),
        ),
        migrations.AlterField(
            model_name='rentalapplication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='model',
            field=models.CharField(max_length=200, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='registration_number',
            field=models.CharField(max_length=50, verbose_name='Регистрационный номер'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='year',
            field=models.IntegerField(verbose_name='Год выпуска'),
        ),
    ]
