# Generated by Django 5.2.1 on 2025-05-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_transport_price_30_plus_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Цвет'),
        ),
    ]
