# Generated by Django 5.2.1 on 2025-05-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_transport_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalapplication',
            name='security_deposit',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Сумма обеспечительного платежа', max_digits=10, verbose_name='Обеспечительный платеж'),
        ),
    ]
