# Generated by Django 5.2.1 on 2025-05-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_rentalapplication_security_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='vin_number',
            field=models.CharField(default=0, help_text='17-значный идентификационный номер транспортного средства', max_length=17, null=True, verbose_name='VIN номер'),
        ),
    ]
