# Generated by Django 5.2.1 on 2025-05-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_transport_vin_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Регистрационный номер'),
        ),
    ]
