# Generated by Django 5.2.1 on 2025-05-28 03:06

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0007_alter_transport_registration_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='number',
            field=models.PositiveIntegerField(blank=True, help_text='Порядковый номер транспорта', null=True, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='rentalapplication',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Контактный номер телефона. Без +', max_length=128, region=None, verbose_name='Телефон'),
        ),
    ]
