# Generated by Django 5.2.1 on 2025-05-28 03:20

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0008_transport_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalapplication',
            name='passport_issue_date',
            field=models.DateField(blank=True, help_text='Дата выдачи паспорта', null=True, verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='rentalapplication',
            name='passport_issued_by',
            field=models.CharField(blank=True, help_text='Орган, выдавший паспорт', max_length=200, null=True, verbose_name='Кем выдан'),
        ),
        migrations.AlterField(
            model_name='rentalapplication',
            name='passport_number',
            field=models.CharField(blank=True, help_text='Номер паспорта', max_length=50, null=True, verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='rentalapplication',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Контактный номер телефона.', max_length=128, region=None, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='rentalapplication',
            name='security_deposit',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, help_text='Сумма обеспечительного платежа', max_digits=10, null=True, verbose_name='Обеспечительный платеж'),
        ),
        migrations.AlterField(
            model_name='rentalapplication',
            name='transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rental_applications', to='rentals.transport', verbose_name='Транспорт'),
        ),
    ]
