# Generated by Django 5.2.1 on 2025-05-28 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0009_alter_rentalapplication_passport_issue_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalapplication',
            name='status',
            field=models.CharField(choices=[('reserved', 'Резерв'), ('active', 'Активная'), ('completed', 'Завершенная'), ('cancelled', 'Отмененная')], default='reserved', help_text='Текущий статус заявки', max_length=20, verbose_name='Статус'),
        ),
    ]
