# Generated by Django 5.2.1 on 2025-06-09 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0012_client_rentalapplication_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название события')),
                ('start', models.DateTimeField(verbose_name='Начало')),
                ('end', models.DateTimeField(verbose_name='Конец')),
                ('all_day', models.BooleanField(default=True, verbose_name='Весь день')),
                ('status', models.CharField(choices=[('reserved', 'Резерв'), ('active', 'Активная'), ('completed', 'Завершенная'), ('cancelled', 'Отмененная')], default='reserved', max_length=20, verbose_name='Статус')),
                ('rental_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='rentals.rentalapplication', verbose_name='Заявка на аренду')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='rentals.transport', verbose_name='Транспорт')),
            ],
            options={
                'verbose_name': 'Событие календаря',
                'verbose_name_plural': 'События календаря',
                'ordering': ['start'],
            },
        ),
    ]
