# Generated by Django 5.2.1 on 2025-06-12 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0013_calendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalapplication',
            name='discount',
            field=models.IntegerField(choices=[(0, 'Без скидки'), (10, '10%'), (20, '20%')], default=0, help_text='Скидка на аренду', verbose_name='Скидка'),
        ),
    ]
