# Generated by Django 5.2.1 on 2025-06-15 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0014_link_existing_rentals'),
        ('rentals', '0014_rentalapplication_discount'),
    ]

    operations = [
    ]
