# Generated by Django 5.2.1 on 2025-06-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0015_merge_20250615_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='passport_issue_date',
            field=models.DateField(blank=True, help_text='Дата выдачи паспорта', null=True, verbose_name='Дата выдачи'),
        ),
        migrations.AddField(
            model_name='client',
            name='passport_issued_by',
            field=models.CharField(blank=True, help_text='Орган, выдавший паспорт', max_length=200, null=True, verbose_name='Кем выдан'),
        ),
        migrations.AddField(
            model_name='client',
            name='passport_number',
            field=models.CharField(blank=True, help_text='Номер паспорта', max_length=50, null=True, verbose_name='Номер паспорта'),
        ),
    ]
