# Generated by Django 5.2.1 on 2025-06-25 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0015_rentalapplication_how_did_you_find_us'),
        ('rentals', '0017_update_client_passport_data'),
    ]

    operations = [
    ]
