# Generated by Django 5.2.1 on 2025-06-25 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0016_client_how_did_you_find_us'),
        ('rentals', '0018_merge_20250625_1317'),
    ]

    operations = [
    ]
