# Generated by Django 5.2.1 on 2025-06-25 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0019_merge_20250625_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='how_did_you_find_us',
            field=models.CharField(blank=True, choices=[('friends', 'От друзей / знакомых'), ('internet', 'Из интернета / через поиск (Google, Яндекс)'), ('ads', 'Увидел рекламу'), ('repeat_customer', 'У вас брал услугу раньше / уже был клиентом'), ('catalog', 'Нашли вас в каталоге / на картах (Google Maps, 2ГИС, Яндекс.Справочник)')], help_text='Как клиент узнал о нас', max_length=32, null=True, verbose_name='Откуда о нас узнали'),
        ),
    ]
