# Generated by Django 5.2.1 on 2025-06-25 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0017_add_other_to_how_did_you_find_us'),
        ('rentals', '0020_alter_client_how_did_you_find_us'),
    ]

    operations = [
    ]
