# Generated by Django 5.2.1 on 2025-06-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0022_rentalapplication_original_total_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalapplication',
            name='security_deposit',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, help_text='Сумма Залога', max_digits=10, null=True, verbose_name='Залог'),
        ),
    ]
