# Generated by Django 5.2.1 on 2025-07-01 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0023_alter_rentalapplication_security_deposit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='city',
            field=models.CharField(choices=[('sochi', 'Сочи'), ('adler', 'Адлер')], default='sochi', max_length=16, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(choices=[('sochi', 'Сочи'), ('adler', 'Адлер')], default='sochi', max_length=16, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='city',
            field=models.CharField(choices=[('sochi', 'Сочи'), ('adler', 'Адлер')], default='sochi', max_length=16, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='transport',
            name='city',
            field=models.CharField(choices=[('sochi', 'Сочи'), ('adler', 'Адлер')], default='sochi', max_length=16, verbose_name='Город'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('sochi', 'Сочи'), ('adler', 'Адлер')], default='sochi', max_length=16, verbose_name='Город')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
