# Generated by Django 5.2.1 on 2025-07-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0025_rentalapplication_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalapplication',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время активации'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='status',
            field=models.CharField(choices=[('reserved', 'Резерв'), ('active', 'Активная'), ('completed', 'Завершенная'), ('cancelled', 'Отмененная'), ('overdue', 'Просрочена')], default='reserved', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='rentalapplication',
            name='status',
            field=models.CharField(choices=[('reserved', 'Резерв'), ('active', 'Активная'), ('completed', 'Завершенная'), ('cancelled', 'Отмененная'), ('overdue', 'Просрочена')], default='reserved', help_text='Текущий статус заявки', max_length=20, verbose_name='Статус'),
        ),
    ]
