# Generated by Django 5.2.1 on 2025-08-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0026_rentalapplication_activated_at_alter_calendar_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advantages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Слаг')),
                ('number', models.PositiveIntegerField(help_text='Порядковый номер преимущества', verbose_name='Номер')),
                ('image', models.ImageField(blank=True, null=True, upload_to='advantages/', verbose_name='Изображение')),
                ('text', models.TextField(help_text='Описание преимущества', verbose_name='Текст')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
                'ordering': ['number'],
            },
        ),
    ]
