# Generated by Django 5.2.1 on 2025-08-18 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0027_advantages'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='transport',
            name='condition',
            field=models.CharField(choices=[('excellent', 'Отличное'), ('good', 'Хорошее'), ('fair', 'Удовлетворительное'), ('poor', 'Плохое')], default='good', max_length=16, verbose_name='Состояние'),
        ),
        migrations.AddField(
            model_name='transport',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='transport',
            name='engine_volume_l',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Объем двигателя (л)'),
        ),
        migrations.AddField(
            model_name='transport',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='transports/', verbose_name='Основное изображение'),
        ),
        migrations.AddField(
            model_name='transport',
            name='mileage_km',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Пробег (км)'),
        ),
        migrations.AddField(
            model_name='transport',
            name='power_hp',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Мощность (л.с.)'),
        ),
        migrations.AddField(
            model_name='transport',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='Слаг'),
        ),
        migrations.AddField(
            model_name='transport',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='transports/thumbnails/', verbose_name='Мини изображение'),
        ),
        migrations.AddField(
            model_name='transport',
            name='transmission',
            field=models.CharField(blank=True, choices=[('automatic', 'Автомат'), ('manual', 'Механика'), ('cvt', 'Вариатор'), ('other', 'Другая')], max_length=16, null=True, verbose_name='Трансмиссия'),
        ),
        migrations.CreateModel(
            name='TransportImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='transports/gallery/', verbose_name='Доп. изображение')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rentals.transport', verbose_name='Транспорт')),
            ],
            options={
                'verbose_name': 'Изображение транспорта',
                'verbose_name_plural': 'Изображения транспорта',
            },
        ),
    ]
