# Generated by Django 5.2.1 on 2025-08-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0028_transport_category_transport_condition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='Слаг')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Категория')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Основное изображение')),
                ('extra_image', models.ImageField(blank=True, null=True, upload_to='blog/extra/', verbose_name='Доп. изображение')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Статья блога',
                'verbose_name_plural': 'Статьи блога',
                'ordering': ['-created_at'],
            },
        ),
    ]
