# Generated by Django 5.2.1 on 2025-08-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0030_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('color', models.CharField(blank=True, max_length=100, null=True, verbose_name='Цвет')),
                ('drive', models.CharField(blank=True, max_length=100, null=True, verbose_name='Привод')),
                ('dimensions_l_w_h_mm', models.CharField(blank=True, max_length=255, null=True, verbose_name='Размеры техники ДхШхВ (мм)')),
                ('seat_height_mm', models.CharField(blank=True, max_length=100, null=True, verbose_name='Высота сидения (мм)')),
                ('handlebar_height_mm', models.CharField(blank=True, max_length=100, null=True, verbose_name='Высота по рулю (мм)')),
                ('axle_size_mm', models.CharField(blank=True, max_length=255, null=True, verbose_name='Размер по осям (мм)')),
                ('engine_displacement_cc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Рабочий объем ДВС (сс)')),
                ('engine_power_hp_kw_rpm', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мощность ДВС (л.с/кВт/об.мин)')),
                ('engine_mark_actual', models.CharField(blank=True, max_length=255, null=True, verbose_name='Маркировка ДВС фактически')),
                ('engine_mark_cover', models.CharField(blank=True, max_length=255, null=True, verbose_name='Маркировка ДВС на крышке')),
                ('cooling', models.CharField(blank=True, max_length=100, null=True, verbose_name='Охлаждение')),
                ('start', models.CharField(blank=True, max_length=100, null=True, verbose_name='Запуск')),
                ('fuel_supply', models.CharField(blank=True, max_length=100, null=True, verbose_name='Подача топлива')),
                ('transmission', models.CharField(blank=True, max_length=100, null=True, verbose_name='Трансмиссия')),
                ('gears_count', models.CharField(blank=True, max_length=100, null=True, verbose_name='Количество передач')),
                ('tank_volume_l', models.CharField(blank=True, max_length=100, null=True, verbose_name='Объем бака (л)')),
                ('wheel_front', models.CharField(blank=True, max_length=100, null=True, verbose_name='Колесо переднее')),
                ('wheel_rear', models.CharField(blank=True, max_length=100, null=True, verbose_name='Колесо заднее')),
                ('max_speed_kmh', models.CharField(blank=True, max_length=100, null=True, verbose_name='МАХ скорость (км/час)')),
                ('front_brake_disc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Передний тормозной диск')),
                ('rear_brake_disc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Задний тормозной диск')),
                ('brake_system', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тормозная система')),
                ('optics', models.CharField(blank=True, max_length=255, null=True, verbose_name='Оптика')),
                ('dashboard', models.CharField(blank=True, max_length=255, null=True, verbose_name='Панель приборов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Продажа транспорта',
                'verbose_name_plural': 'Продажи транспорта',
                'ordering': ['-created_at'],
            },
        ),
    ]
