# Generated by Django 5.2.1 on 2025-08-25 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0031_transportsale'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Advantages',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='TransportSale',
        ),
    ]
